services:
  postgres:
    image: kartoza/postgis
    platform: linux/arm64
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: geodb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d geodb"]
      interval: 5s
      retries: 5
      start_period: 10s

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    restart: always
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - geoserver_data:/opt/geoserver_data
    ports:
      - '8080:8080'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  python:
    build: ./db
    container_name: python
    volumes:
      - ./db:/app
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "sleep 10 && python import_geojson.py"]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - geoserver

volumes:
  pg_data:
  geoserver_data:
